library dash;

import 'dart:html' as HTML;
import 'dart:mirrors' as Mirrors;
import 'dart:math' as Math;
import 'dart:collection' as Collection;

part 'src/simulation/entity.dart';
part 'src/simulation/simulation.dart';
part 'src/game.dart';
part 'src/simulation/database.dart';
part 'src/simulation/aspect.dart';
part 'src/events/event_manager.dart';
part 'src/events/event.dart';
part 'src/simulation/entity_addition.dart';
part 'src/simulation/entity_destruction.dart';
part 'src/simulation/entity_change.dart';
part 'src/simulation/processor.dart';
part 'src/simulation/entity_observer_processor.dart';
part 'src/events/event_subscription_manager.dart';
part 'src/simulation/update.dart';
part 'src/class_id_map.dart';
part 'src/color.dart';
part 'src/math/vector4.dart';
part 'src/keyboard/keyboard.dart';
part 'src/keyboard/event_registry.dart';
part 'src/helpers/html_helper.dart';
part 'src/math/vector.dart';
part 'src/math/vector2.dart';
part 'src/simulation/entity_processor.dart';
part 'src/geometry/polygon.dart';
part 'src/geometry/line_segment.dart';
part 'src/geometry/point2d.dart';
part 'src/geometry/polygon/polygon_line_collection.dart';
part 'src/geometry/polygon/polygon_line_collection_iterator.dart';
part 'src/geometry/polygon/polygon_normal_collection.dart';
part 'src/geometry/polygon/polygon_normal_collection_iterator.dart';
part 'src/events/event_subscription.dart';
part 'src/geometry/projection.dart';
part 'src/rendering/resolution.dart';
part 'src/rendering/rendering_setup.dart';
